# Generated by Django 5.1.5 on 2025-02-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_alter_college_academicstaff_alter_college_campussize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='division',
            field=models.CharField(choices=[('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3')], default='D1', max_length=10),
        ),
        migrations.AlterField(
            model_name='college',
            name='type',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=10),
        ),
    ]
